jog_joint_node:
  joint_names:
    - shoulder_yaw_joint
    - shoulder_pitch_joint
    - elbow_pitch_joint
    - wrist_pitch_joint

jog_frame_node:
  group_names:
    - arm
  link_names:
    - gripper_guide_link

# Somehow, UR5 moveit doesn't have controller name, so specify here
move_group:
  controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
        - shoulder_yaw_joint
        - shoulder_pitch_joint
        - elbow__pitch_joint
        - wrist_pitch_joint
